DROP_USER_TABLE = ''' DROP TABLE IF EXISTS USER '''

DROP_PATIENT_TABLE = ''' DROP TABLE IF EXISTS PATIENT '''

DROP_DOCTOR_TABLE = ''' DROP TABLE IF EXISTS DOCTOR '''

DROP_HOSPITAL_STAY_TABLE = ''' DROP TABLE IF EXISTS HOSPITAL_STAY '''

DROP_VISITATION_TABLE = ''' DROP TABLE IF EXISTS VISITATION '''

CREATE_USER_TABLE = '''
    CREATE TABLE IF NOT EXISTS USER (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        USERNAME TEXT NOT NULL,
        PASSWORD TEXT NOT NULL,
        AGE INTEGER,
        IS_ACTIVE INTEGER NOT NULL DEFAULT 0
    )
'''

CREATE_DOCTOR_TABLE = '''
    CREATE TABLE IF NOT EXISTS DOCTOR (
        ID INTEGER PRIMARY KEY,
        ACCADEMIC_TITLE TEXT,
        FOREIGN KEY (ID) REFERENCES USER(ID)
    )
'''

CREATE_PATIENT_TABLE = '''
    CREATE TABLE IF NOT EXISTS PATIENT (
        ID INTEGER PRIMARY KEY,
        DOCTOR_ID INTEGER,
        FOREIGN KEY (ID) REFERENCES USER(ID),
        FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(ID)
    )
'''

CREATE_HOSPITAL_STAY_TABLE = '''
    CREATE TABLE IF NOT EXISTS HOSPITAL_STAY (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        STARTDATE TEXT NOT NULL,
        ENDDATE TEXT,
        ROOM INTEGER NOT NULL,
        INJURY TEXT NOT NULL,
        PATIENT_ID INTEGER,
        FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(ID)
    )
'''

CREATE_VISITATION_TABLE = '''
    CREATE TABLE IF NOT EXISTS VISITATION (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        PATIENT_ID INTEGER,
        DOCTOR_ID INTEGER NOT NULL,
        START_HOUR TEXT NOT NULL,
        FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(ID),
        FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(ID)
    )
'''

LIST_PATIENT_IDS = ''' SELECT ID FROM PATIENT '''

LIST_DOCTOR_IDS = ''' SELECT ID FROM DOCTOR '''

LIST_HOSPITAL_STAY_IDS = ''' SELECT ID FROM HOSPITAL_STAY '''

LIST_USER_IDS = ''' SELECT ID FROM USER '''

LIST_VISITATION_IDS = ''' SELECT ID FROM VISITATION '''

ADD_USER = '''
    INSERT INTO USER(USERNAME, PASSWORD, AGE)
    VALUES(?, ?, ?)
'''

ADD_PATIENT = '''
    INSERT INTO PATIENT(ID, DOCTOR_ID)
    VALUES(?, ?)
'''

ADD_DOCTOR = '''
    INSERT INTO DOCTOR(ID, ACCADEMIC_TITLE)
    VALUES(?, ?)
'''

ADD_HOSPITAL_STAY = '''
    INSERT INTO HOSPITAL_STAY(STARTDATE, ENDDATE, ROOM, INJURY, PATIENT_ID)
    VALUES(?, ?, ?, ?, ?)
'''

ADD_VISITATION = '''
    INSERT INTO VISITATION(PATIENT_ID, DOCTOR_ID, START_HOUR)
    VALUES(?, ?, ?)
'''

ID_OF_USER_BY_USERNAME = '''
    SELECT ID
    FROM USER
    WHERE USERNAME=?
'''

PASSWORD_OF_USER = '''
    SELECT PASSWORD
    FROM USER
    WHERE ID=?
'''

DOCTOR_ACCADEMIC_TITLE = '''
    SELECT ACCADEMIC_TITLE
    FROM DOCTOR
    WHERE ID == ?
'''

LIST_HS_FOR_PATIENT = '''
    SELECT STARTDATE, ENDDATE, ROOM, INJURY
    FROM HOSPITAL_STAY
    WHERE PATIENT_ID == ?
'''

DELETE_FREE_VISITATIONS_OF_DOCTOR = '''
    DELETE FROM VISITATION
    WHERE DOCTOR_ID == ? AND PATIENT_ID IS NULL
'''

LIST_FREE_VISITATIONS_OF_DOCTOR = '''
    SELECT ID, START_HOUR
    FROM VISITATION
    WHERE DOCTOR_ID==? AND PATIENT_ID IS NULL
'''

MAKE_ALL_USERS_NOT_LOGGED = '''
    UPDATE USER
    SET IS_ACTIVE=0
'''

LIST_ALL_PATIENTS = '''
    SELECT ID, USERNAME, AGE
    FROM USER
    JOIN PATIENT ON USER.ID == PATIENT.ID
'''

LIST_ALL_DOCTORS = '''
    SELECT DOCTOR.ID, USERNAME, ACCADEMIC_TITLE
    FROM USER
    JOIN DOCTOR ON USER.ID == DOCTOR.ID
'''

USER_STATUS = '''
    SELECT IS_ACTIVE
    FROM USER
    WHERE ID=?
'''

UPDATE_USER_USERNAME = '''
    UPDATE USER
    SET USERNAME=?
    WHERE ID=?
'''

UPDATE_USER_PASSWORD = '''
    UPDATE USER
    SET PASSWORD=?
    WHERE ID=?
'''

UPDATE_USER_AGE = '''
    UPDATE USER
    SET AGE=?
    WHERE ID=?
'''

UPDATE_USER_IS_ACTIVE = '''
    UPDATE USER
    SET IS_ACTIVE=?
    WHERE ID=?
'''

UPDATE_PATIENT_DOCTOR_ID = '''
    UPDATE PATIENT
    SET DOCTOR_ID=?
    WHERE ID=?
'''

UPDATE_DOCTOR_ACCADEMIC_TITLE = '''
    UPDATE DOCTOR
    SET ACCADEMIC_TITLE=?
    WHERE ID=?
'''

DOCTOR_DATA = '''
    SELECT USER.USERNAME, USER.AGE, USER.ID, DOCTOR.ACCADEMIC_TITLE
    FROM DOCTOR
    JOIN USER ON DOCTOR.ID == USER.ID
    WHERE DOCTOR.ID==?
'''

PATIENT_DATA = '''
    SELECT USER.USERNAME, USER.AGE, USER.ID, PATIENT.DOCTOR_ID
    FROM PATIENT
    JOIN USER ON PATIENT.ID == USER.ID
    WHERE PATIENT.ID==?
'''

UPDATE_VISITATION_PATIENT_ID = '''
    UPDATE VISITATION
    SET PATIENT_ID=?
    WHERE ID=?
'''

LIST_PATIENTS_OF_DOCTOR = '''
    SELECT USER.ID, USER.USERNAME, USER.AGE
    FROM PATIENT
    JOIN USER ON PATIENT.ID == USER.ID
    WHERE DOCTOR_ID == ?;
'''

ROOM_AND_HS_DURATION_OF_DOCTOR_PATIENTS = '''
    SELECT USER.USERNAME, ROOM, HS.STARTDATE, HS.ENDDATE
    FROM PATIENT
    JOIN USER ON PATIENT.ID == USER.ID
    JOIN HOSPITAL_STAY AS HS ON HS.PATIENT_ID = PATIENT.ID
    WHERE DOCTOR_ID == ?;
'''
