DROP_USER_TABLE = ''' DROP TABLE IF EXISTS USER '''

DROP_PATIENT_TABLE = ''' DROP TABLE IF EXISTS PATIENT '''

DROP_DOCTOR_TABLE = ''' DROP TABLE IF EXISTS DOCTOR '''

DROP_HOSPITAL_STAY_TABLE = ''' DROP TABLE IF EXISTS HOSPITAL_STAY '''

DROP_VISITATION_TABLE = ''' DROP TABLE IF EXISTS VISITATION '''

CREATE_USER_TABLE = '''
    CREATE TABLE IF NOT EXISTS USER (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        USERNAME TEXT NOT NULL,
        PASSWORD TEXT NOT NULL,
        AGE INTEGER,
        IS_ACTIVE INTEGER NOT NULL DEFAULT 0
    )
'''

CREATE_DOCTOR_TABLE = '''
    CREATE TABLE IF NOT EXISTS DOCTOR (
        ID INTEGER PRIMARY KEY,
        ACADEMIC_TITLE TEXT,
        FOREIGN KEY (ID) REFERENCES USER(ID)
    )
'''

CREATE_PATIENT_TABLE = '''
    CREATE TABLE IF NOT EXISTS PATIENT (
        ID INTEGER PRIMARY KEY,
        DOCTOR_ID INTEGER,
        FOREIGN KEY (ID) REFERENCES USER(ID),
        FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(ID)
    )
'''

CREATE_HOSPITAL_STAY_TABLE = '''
    CREATE TABLE IF NOT EXISTS HOSPITAL_STAY (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        STARTDATE TEXT NOT NULL,
        ENDDATE TEXT,
        ROOM INTEGER NOT NULL,
        INJURY TEXT NOT NULL,
        PATIENT_ID INTEGER,
        FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(ID)
    )
'''

CREATE_VISITATION_TABLE = '''
    CREATE TABLE IF NOT EXISTS VISITATION (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        PATIENT_ID INTEGER,
        DOCTOR_ID INTEGER NOT NULL,
        START_HOUR TEXT NOT NULL,
        FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(ID),
        FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(ID)
    )
'''

LIST_PATIENT_IDS = ''' SELECT ID FROM PATIENT '''

LIST_DOCTOR_IDS = ''' SELECT ID FROM DOCTOR '''

LIST_HOSPITAL_STAY_IDS = ''' SELECT ID FROM HOSPITAL_STAY '''

LIST_USER_IDS = ''' SELECT ID FROM USER '''

LIST_VISITATION_IDS = ''' SELECT ID FROM VISITATION '''

ADD_USER = '''
    INSERT INTO USER(USERNAME, PASSWORD, AGE)
    VALUES(?, ?, ?)
'''

ADD_PATIENT = '''
    INSERT INTO PATIENT(ID, DOCTOR_ID)
    VALUES(?, ?)
'''

ADD_DOCTOR = '''
    INSERT INTO DOCTOR(ID, ACADEMIC_TITLE)
    VALUES(?, ?)
'''

ADD_HOSPITAL_STAY = '''
    INSERT INTO HOSPITAL_STAY(STARTDATE, ENDDATE, ROOM, INJURY, PATIENT_ID)
    VALUES(?, ?, ?, ?, ?)
'''

ADD_VISITATION = '''
    INSERT INTO VISITATION(PATIENT_ID, DOCTOR_ID, START_HOUR)
    VALUES(?, ?, ?)
'''

DELETE_USER = ''' DELETE FROM USER WHERE ID=? '''

DELETE_PATIENT = ''' DELETE FROM PATIENT WHERE ID=? '''

DELETE_DOCTOR = ''' DELETE FROM DOCTOR WHERE ID=? '''

DELETE_HOSPITAL_STAY = ''' DELETE FROM HOSPITAL_STAY WHERE ID=? '''

DELETE_VISITATION = ''' DELETE FROM VISITATION WHERE ID=? '''

DOCTOR_ACCADEMIC_TITLE = '''
    SELECT ACCADEMIC_TITLE
    FROM DOCTOR
    WHERE ID == ?
'''
LIST_HS_FOR_PATIENT = '''
    SELECT STARTDATE, ENDDATE, ROOM, INJURY
    FROM HOSPITAL_STAY
    WHERE PATIENT_ID == ?
'''
DELETE_FREE_VISITATIONS_OF_DOCTOR = '''
    DELETE FROM VISITATION
    WHERE DOCTOR_ID == ? AND PATIENT_ID IS NULL
'''

LIST_FREE_VISITATIONS_OF_DOCTOR = '''
    SELECT ID, START_HOUR
    FROM VISITATION
    WHERE DOCTOR_ID==?
'''

LIST_ALL_USERS = '''
    SELECT ID, USERNAME, AGE
    FROM USER
'''

LIST_ALL_PATIENTS = '''
    SELECT ID, USERNAME, AGE
    FROM USER
    JOIN PATIENT ON USER.ID == PATIENT.ID
'''

LIST_ALL_DOCTORS = '''
    SELECT ID, USERNAME, ACADEMIC_TITLE
    FROM USER
    JOIN DOCTOR ON USER.ID == DOCTOR.ID
'''

LIST_ALL_VISITATIONS = '''
    SELECT ID, PATIENT_ID, DOCTOR_ID, START_HOUR
    FROM VISITATION
'''

UPDATE_USER_USERNAME = '''
    UPDATE USER
    SET USERNAME=?
    WHERE ID=?
'''

UPDATE_USER_PASSWORD = '''
    UPDATE USER
    SET PASSWORD=?
    WHERE ID=?
'''

UPDATE_USER_AGE = '''
    UPDATE USER
    SET AGE=?
    WHERE ID=?
'''

UPDATE_PATIENT_DOCTOR_ID = '''
    UPDATE PATIENT
    SET DOCTOR_ID=?
    WHERE ID=?
'''

UPDATE_DOCTOR_ACADEMIC_TITLE = '''
    UPDATE DOCTOR
    SET ACADEMIC_TITLE=?
    WHERE ID=?
'''

UPDATE_HS_STARTDATE = '''
    UPDATE HOSPITAL_STAY
    SET STARTDATE=?
    WHERE ID=?
'''

UPDATE_HS_ENDDATE = '''
    UPDATE HOSPITAL_STAY
    SET ENDDATE=?
    WHERE ID=?
'''

UPDATE_HS_ROOM = '''
    UPDATE HOSPITAL_STAY
    SET ROOM=?
    WHERE ID=?
'''

UPDATE_HS_INJURY = '''
    UPDATE HOSPITAL_STAY
    SET INJURY=?
    WHERE ID=?
'''

UPDATE_HS_PATIENT_ID = '''
    UPDATE HOSPITAL_STAY
    SET PATIENT_ID=?
    WHERE ID=?
'''

UPDATE_VISITATION_PATIENT_ID = '''
    UPDATE VISITATION
    SET PATIENT_ID=?
    WHERE ID=?
'''

UPDATE_VISITATION_DOCTOR_ID = '''
    UPDATE VISITATION
    SET DOCTOR_ID=?
    WHERE ID=?
'''

UPDATE_VISITATION_START_HOUR = '''
    UPDATE VISITATION
    SET START_HOUR=?
    WHERE ID=?
'''

LIST_PATIENTS_OF_DOCTOR = '''
    SELECT USER.ID, USER.USERNAME, USER.AGE
    FROM PATIENT
    JOIN USER ON PATIENT.ID == USER.ID
    WHERE DOCTOR_ID == ?;
'''

ROOM_AND_HS_DURATION_OF_DOCTOR_PATIENTS = '''
    SELECT USER.USERNAME, ROOM, HS.STARTDATE, HS.ENDDATE
    FROM PATIENT
    JOIN USER ON PATIENT.ID == USER.ID
    JOIN HOSPITAL_STAY AS HS ON HS.PATIENT_ID = PATIENT.ID
    WHERE DOCTOR_ID == ?;
'''

PATIENTS_GROUP_BY_INJURY = '''
    SELECT PATIENT.ID, USER.USERNAME, USER.AGE
    FROM HOSPITAL_STAY
    LEFT JOIN PATIENT ON PATIENT.ID = HOSPITAL_STAY.PATIENT_ID
    LEFT JOIN USER ON USER.ID = PATIENT.ID
    WHERE HOSPITAL_STAY.INJURY=?
'''

DOCTORS_DISIESES = '''
    SELECT USER.USERNAME, GROUP_CONCAT(DISTINCT HOSPITAL_STAY.INJURY)
    FROM DOCTOR
    LEFT JOIN USER ON USER.ID = DOCTOR.ID
    LEFT JOIN PATIENT ON DOCTOR.ID = PATIENT.DOCTOR_ID
    LEFT JOIN HOSPITAL_STAY ON PATIENT.ID = HOSPITAL_STAY.PATIENT_ID
    GROUP BY DOCTOR.ID
'''

PATIENTS_BETWEEN_DATES = '''
    SELECT USER.USERNAME, USER.AGE
    FROM PATIENT
    JOIN USER ON USER.ID = PATIENT.ID
    JOIN HOSPITAL_STAY AS HS ON PATIENT.ID = HS.PATIENT_ID
    WHERE HS.STARTDATE > DATETIME(?) AND HS.ENDDATE < DATETIME(?)
'''
